### ISSUE TITLE
`KeyError: '_sample_df'` when attempting to upload a project

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pepdbagent#31]
I was attempting to load a new database with new PEPs that conforms to the latest schema (tags) and I received the following error:

```console
line 799, in _create_digest
    json.dumps(project_dict["_sample_df"], sort_keys=True).encode("utf-8")
KeyError: '_sample_df'
```

Running isolated in the REPL:

```python
>>> import peppy
>>> from pepdbagent import Connection
>>> pepagent = Connection(
...     user="postgres",
...     password="docker",
...     database="pep-base-sql"
... )
>>> proj = peppy.Project("examples/demo/basic/project_config.yaml")
>>> pepagent.upload_project(proj, namespace="demo", name="basic")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.9/site-packages/pepdbagent/pepdbagent.py", line 101, in upload_project
    proj_digest = self._create_digest(proj_dict)
  File ".venv/lib/python3.9/site-packages/pepdbagent/pepdbagent.py", line 799, in _create_digest
    json.dumps(project_dict["_sample_df"], sort_keys=True).encode("utf-8")
KeyError: '_sample_df'
>>> 
```

**Comment by nleroy917** [comment]
I think it's occurring right here: https://github.com/pepkit/peppy/blob/c7ecbd3e0d5ceb0c3561ff290cac8c58c634d478/peppy/project.py#L300

In `p_dict`, `_sample_df` is never set. The closest thing is `_sample_dict`.

Locally, changing `pepdbagent.Connection._create_digest` to look for `_sample_dict` instead seems to fix things, for a bit. But then it later stumbles on the `_subsample_df` key:

```console
Traceback (most recent call last):
  File ".venv/lib/python3.9/site-packages/attmap/ordattmap.py", line 46, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: '_subsample_df'
```
